# site name
prefixName: KINGWDYã®
siteName: ãƒ–ãƒ­ã‚°
# favicon and site master avatar
favicon: https://i.postimg.cc/xT7tgjWb/5-11.gif
avatar: https://i.postimg.cc/xT7tgjWb/5-11.gif
url: https://kingwdy.avosapps.us
description: #
cdn: 
pjax: 1
# 1å¼€å¯
mathjax: 0

notice: 12313
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  å½’æ¡£: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code }, 
    ç”Ÿæ´»: {path: /categories/ç”Ÿæ´»/, fa: fa-file-text-o }, 
    èµ„æº: {path: /categories/èµ„æº/, fa: fa-cloud-download }, 
    éšæƒ³: {path: /categories/éšæƒ³/, fa: fa-commenting-o },
    è½¬è½½: {path: /categories/è½¬è½½/, fa: fa-book },
    æ ‡ç­¾: {path: /tags/, fa: fa-tag },
    åˆ†ç±»: {path: /categories/, fa: fa-bookmark }
  } }
  æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    ä¹¦å•: {path: /tags/æ‚¦è¯»/, fa: fa-th-list faa-bounce }, 
    ç•ªç»„: {path: /bangumi/, fa: fa-film faa-vertical }, 
    æ­Œå•: {path: /music/, fa: fa-headphones },
    vlog: {path: /videos/, fa: fa-youtube-play }
  } }
  ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
  èµèµ: { path: /donate/, fa: fa-heart faa-pulse }
  å…³äºæˆ‘: { path: /about/, fa: fa-meetup , submenus: } 
  æ›´å¤š: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    å·¥å…·: { path: /more/, fa: fa-gear },
    è¯´è¯´: {path: /shuoshuo/, fa: fa-commenting-o fa-commenting },
    å¯¼èˆª: {path: /box/, fa: fas fa-location-arrow },
    ğŸš‡å¼€å¾€: {path: https://travellings.link }
  } }
  


# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1s

# èƒŒæ™¯å›¾ç‰‡ ã€é€‰ã€‘
bgn: 8
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg:
  - https://w.wallhaven.cc/full/13/wallhaven-13o6xg.png
  - https://w.wallhaven.cc/full/5w/wallhaven-5w8ko9.png
  - https://w.wallhaven.cc/full/md/wallhaven-md3wd9.jpg
  - https://w.wallhaven.cc/full/yj/wallhaven-yj87gg.png
  - https://w.wallhaven.cc/full/5d/wallhaven-5d2jw5.jpg
  - https://w.wallhaven.cc/full/ey/wallhaven-ey76e8.png
  - https://w.wallhaven.cc/full/zx/wallhaven-zxd19o.jpg
  - https://w.wallhaven.cc/full/13/wallhaven-13xwwv.jpg
  - https://w.wallhaven.cc/full/dp/wallhaven-dp6d3m.jpg
  - https://w.wallhaven.cc/full/lm/wallhaven-lmkzky.jpg
  - https://w.wallhaven.cc/full/p8/wallhaven-p8x52j.png
  - https://w.wallhaven.cc/full/nr/wallhaven-nrpl70.jpg
  - https://w.wallhaven.cc/full/y8/wallhaven-y8g5ok.png
  - https://w.wallhaven.cc/full/3z/wallhaven-3z3zq9.jpg
  - https://w.wallhaven.cc/full/8x/wallhaven-8xd17o.jpg
  - https://w.wallhaven.cc/full/eo/wallhaven-eopr6l.jpg
  - https://api.flymc.cc/hotlink-ok/cover/79583493_p0.jpg
  - https://api.flymc.cc/hotlink-ok/cover/83908460_p0.jpg
  - https://api.flymc.cc/hotlink-ok/cover/86800103_p0.jpg
  - https://api.flymc.cc/hotlink-ok/cover/â˜…%20@Gieep.jpg
  - https://api.flymc.cc/hotlink-ok/cover/313275_animal_ears_brown_hair_catgir.jpg

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: æœ¬ç«™ä½¿ç”¨çš„ hexo ä¸»é¢˜, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/524861725?spm_id_from=333.1007.0.0, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/bilibili.jpg}
  - {url: http://chat.daovoice.io?id=8a05dc92, title: KWå®¢æœ, desc: æŠ€æœ¯æœåŠ¡, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/wangshiwu.jpg}
  - {url: kwptuku, title: æˆ‘çš„ç›¸å†Œ, desc: åˆ†äº«å¼€å¿ƒæ—¶åˆ», img: https://gitlab.com/KINGWDY/tgbb/-/raw/main/ç›¸å†Œå°é¢.webp}
  - {url: KWGAME, title: åœ¨çº¿å°æ¸¸æˆ, desc: åˆ›é€ å¿«ä¹æ—¶å…‰, img: https://gitlab.com/KINGWDY/tgbb/-/raw/main/ps5.webp}
  - {url: https://yqmmkingdom.github.io/Blog-update-log/, title: æ—¥å¿—, desc: è®°å½•æœ¬åšå®¢çš„æ›´æ–°ä¿¡æ¯, img: https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic2.zhimg.com%2Fv2-b1b92836bcdbcd1bec62ad59a36a6e98_1440w.jpg%3Fsource%3D172ae18b&refer=http%3A%2F%2Fpic2.zhimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1656129639&t=2d7a1afa75fb1085df755d95ccac77b6}
  - {url: map, title: åœ°å›¾å’Œå®æ—¶æ•°æ®, desc: è®°å½•è®¿å®¢æ•°æ®å’ŒæœåŠ¡å™¨çŠ¶æ€, img: https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.zcool.cn%2Fcommunity%2F0114a3598143d3a8012156030ff420.jpg&refer=http%3A%2F%2Fimg.zcool.cn&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1656204790&t=739970fbdd74ba29280cb66b07fd1c30}



# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PCç«¯é…ç½®
social:
  github: {url: http://github.com/YQMMKINGDOM, img: https://cdn.jsdelivr.net/gh/YQMMKINGDOM/jsDelivr@main/github.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=5064450374, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wangyiyun.png}
  email: {url: https://gitlab.com/KINGWDY/tgbb/-/raw/acb16540267d358241b047a0a9d5ab6cc4b44e05/é‚®ç®±ä¿¡æ¯.md,  img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/email.svg }
  blibli: {url: https://space.bilibili.com/524861725?spm_id_from=333.1007.0.0, img: https://gitlab.com/KINGWDY/tgbb/-/raw/main/bilibili.png}
  wechat: {url: /#, qrcode: https://gitlab.com/KINGWDY/tgbb/-/raw/main/1E9CB5CE-0839-4D9D-8DDB-4B514B25EE38.webp, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wechat.png}
  CSDN: {url: https://blog.csdn.net/weixin_46397475?spm=1001.2101.3001.5343, img: https://g.csdnimg.cn/static/logo/favicon32.ico}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: http://github.com/YQMMKINGDOM, fa: fa-github, color: 333}
  wechat: {url: https://gitlab.com/KINGWDY/tgbb/-/raw/main/1E9CB5CE-0839-4D9D-8DDB-4B514B25EE38.webp, fa: fa-wechat, color: dd4b39}
  email: {url: https://gitlab.com/KINGWDY/tgbb/-/raw/acb16540267d358241b047a0a9d5ab6cc4b44e05/é‚®ç®±ä¿¡æ¯.md, fa: fa-email, color: 25c6fe}

donate:
  wechat: https://gitlab.com/KINGWDY/tgbb/-/raw/main/EBA5FF7A-2505-43A8-99F5-257745FAFAAA.webp

# è§†é¢‘åœ°å€ä¸ºhttps://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4ï¼Œé…ç½®å¦‚ä¸‹
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: Unbroken.mp4

aplayer: 
  id: 7437759374
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: rE28AlFx3emaxTx9NQPPYfef-MdYXbMMI
v_appKey: Blb6VBNddsWX7RriyHt7RsfD
v_verify: true 


# Waline
waline:
  enable: true
  serverURL: #æœåŠ¡ç«¯åœ°å€
  visitor: true #ç»Ÿè®¡é˜…è¯»é‡
  comment_count: true #ç»Ÿè®¡è¯„è®ºæ•°
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: ç¥å¼€å¼€å¿ƒå¿ƒï¼ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #è®¾ç½®å¿…å¡«é¡¹
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #è¾“å…¥æ¡†æç¤ºåŠ¨ç”»

# leancloudæ•°æ®ç»Ÿè®¡
leancloud_visitors:
  enable: true 
  app_id: Oxg7bmY4E2n2pXoOq7KOT7Mu-MdYXbMMI
  app_key: kU0cFKSa2ip3IxMut8MTEto9

# Online contact ##åœ¨çº¿èŠå¤©
daovoice: true
daovoice_app_id: 8a05dc92  ##è¿™é‡Œæ›¿æ¢æˆä½ DaoVoiceä¸Šçš„appid

# åŠ¨æ€è¯´è¯´é¡µé¢
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://artitalk.js.org
artitalk:
  appID: rE28AlFx3emaxTx9NQPPYfef-MdYXbMMI
  appKEY: Blb6VBNddsWX7RriyHt7RsfD
  per: 7 #æ¯é¡µæ˜¾ç¤ºè¯´è¯´çš„æ•°é‡
  username: root # Leancloudä¸­è®¾ç½®çš„ç”¨æˆ·å
  placeholder1: æ²¡æœ‰å¯†ç ï¼Œä¸èƒ½è¯„è®ºï¼ # å¯†ç æ¡†æç¤ºè¯­
  lazy: 1 # åŠ è½½åŠ¨ç”»1:åŠ è½½,0:å–æ¶ˆåŠ è½½
  img: https://i.postimg.cc/xT7tgjWb/5-11.gif #ç”¨æˆ·é»˜è®¤å¤´åƒ
  bgimg: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich16.gif # è¾“å…¥æ¡†å°åŠ¨ç”»
  # æç®€é»‘ç™½ä¸»é¢˜minimalistã€æ¸å˜ä¸»é¢˜gradientã€å£çº¸wallpaper 
  # å‚è€ƒ https://blog.csdn.net/cungudafa/article/details/106224223
  style: 
    enable: true #ä¸ªæ€§å®šåˆ¶
    wallpaper: https://ae01.alicdn.com/kf/H21b5f6b8496141a1979a33666e1074d9x.jpg #https://bing.rthe.net/wallpaper  # å£çº¸
    color: white   #å­—ä½“é¢œè‰²
    linear_gradient: rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35) 95% # æ¸å˜è§„å¾‹é¢œè‰²+ç™¾åˆ†æ¯” rgb(109, 208, 242) 15%, rgb(245, 154, 190) 85%
    border_right_color: '#FFC0BE' #ä¸‰è§’é¢œè‰²
    animation: false #trueæ‰“å¼€åŠ¨ç”»æ¸å˜æ¸²æŸ“(å£çº¸å’ŒåŠ¨ç”»æ¸å˜æ¸²æŸ“å»ºè®®åªå¼€ä¸€ä¸ª)

	# æ˜¯å¦å¼€å¯å­—æ•°ç»Ÿè®¡
	#ä¸éœ€è¦ä½¿ç”¨ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
	word_count: true

# åŠ è½½åŠ¨ç”»
loading:
  enable: true
  time: 500 # å¼ºåˆ¶å¼€å¯loadingåŠ¨ç”»çš„æ—¶é—´ 1000=1s,é»˜è®¤ä¸º0.5s

# Whether to display post-calender in the `archive` page
# è®¾ç½®åœ¨å½’æ¡£é¡µé¢achiveä¸­æ˜¯å¦æ˜¾ç¤º'æ–‡ç« æ—¥å†'æ§ä»¶
postCalendar: true 

